[package]
name = "core"
version = "0.0.1"
authors = ["Akram Ansari <[EMAIL_ADDRESS]>"]
description = "The database core code"
edition = "2024"

[dependencies]
dashmap = "6.1.0"
parking_lot = "0.12.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
